version: '3'

services:
  db:
    container_name: composed-wp-mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9rkX3Gqz7gDyG0BMbyT3TWTCYSKUlDPd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: tQ9MVITIumcH9z60mvunVamcFoGwOR4Y

  wordpress:
    container_name: composed-wp
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: tQ9MVITIumcH9z60mvunVamcFoGwOR4Y
volumes:
  db_data:
